name: amp-ae-appdata-music-paf-listening-sessions-2y
parentDirs: 
  - /group/amp_ae_appdata_music/paf-listening-sessions/final/version=v1/
retentionDays: 735
retentionDirs: 0 
captureDateRegexp: event_end_date_local=(\d{4}-\d{2}-\d{2})
dateFormat: yyyy-MM-dd
dryRun: false
recursiveSearch: false
adding new line
