name: amp-ae-appdata-podcasts-t1-xp-amp-podcasts-play-v2-730d
parentDirs:
- /group/amp_ae_appdata_podcasts/t1/xp_amp_podcasts_play/v2
retentionDays: '730'
retentionDirs: '0'
captureDateRegexp: date=([0-9]{4}-[0-9]{2}-[0-9]{2})
dateFormat: yyyy-MM-dd
dryRun: false
recursiveSearch: false
