name: amp-ae-payments-commerce-t2-commerce-purchase-incremental-billing-v3-final-2y
parentDirs:
- /group/amp_ae_payments_commerce/t2/commerce_purchase/incremental_billing_v3/final/
retentionDays: '730'
retentionDirs: '0'
captureDateRegexp: initial_dt=(\d{4}-\d{2}-\d{2})
dateFormat: yyyy-MM-dd
dryRun: false
recursiveSearch: false
