name: amp-hadoop-sre-retention
adminUsers:
  - vsaraf
adminGroups:
  - hdp-amp-analytics-sre
flows:
  - name: delete-ae-core-subscription-ds
    schedule: 0 0 0 * * ?
    concurrency: skip
  - name: delete-ingest-mozart
    schedule: 0 0 0 * * ?
    concurrency: skip
  - name: delete-data-platform-jdata-snapshot
    schedule: 0 0 0 * * ?
    concurrency: skip
  - name: delete-amp-ae-appdata-video-content-aggregates-abm-2y
    schedule:
    concurrency: skip
  - name: delete-amp-ae-video-content-aggregates-abm-2y
    schedule:0 43 16 * * ?
    concurrency: skip
  - name: delete-amp-ae-video-content-aggregates-abm-2y
    schedule:0 43 16 * * ?
    concurrency: skip
  - name: delete-amp-ae-video-content-aggregates-abm-2y
    schedule:0 43 16 * * ?
    concurrency: skip

  - name: amp-ae-appdata-video-content-aggregates-abm-2y
    schedule:0 43 16 * * ?
    concurrency: skip
  - name: amp-ae-appdata-video-content-aggregates-abm-2y
    schedule: 0 43 16 * * ?
    concurrency: skip
  - name: amp-ae-appdata-video-content-aggregates-abm-2y
    schedule: 0 43 10 * * ?
    concurrency: skip
  - name: amp-ae-music-agg-v2-30d
    schedule: 0 43 10 * * ?
    concurrency: skip
  - name: amp-popularity-hadoop-aggregates-v1-ContentDeepDivePlayBatchAggregator-7d
    schedule: 0 53 10 * * ?
    concurrency: skip
  - name: amp-ae-payments-commerce-t2-commerce-purchase-incremental-billing-v3-final-2y
    schedule: 0 10 1 * * ?
    concurrency: skip
  - name: amp-ae-appdata-video-t2-content-genome-subscriptions-snapshot-v1-10d
    schedule: * 10 2 * * ?
    concurrency: skip
  - name: amp-ae-appdata-video-t2-content-genome-show-completion-aggregate-DAILY-v1-10d
    schedule: ******
    concurrency: skip