type=command

env.HADOOP_CONF_DIR=/etc/hadoop/conf

# would be used on non-Kerberized envs
env.HADOOP_USER_NAME=worun

# would be used on Kerberized envs
command=hadoop_kinit --no-prompt amp_ae_payments_commerce

command.1=java \
    -cp .:lib/*:/etc/hadoop/conf \
    com.apple.amp.data.retention.HdfsRetentionTool \
    /amp-ae-payments-commerce-t2-commerce-purchase-incremental-billing-v3-final-2y.yml
